# Generated by Django 3.0 on 2021-08-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='order_status',
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
