# Generated by Django 3.0 on 2021-08-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0004_auto_20210811_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumcart',
            name='user_id',
        ),
    ]
