# Generated by Django 3.0 on 2021-08-12 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0006_albumcart_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumcartuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='albumcartuser',
            name='album_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JazzBluesApp.Album'),
        ),
        migrations.RemoveField(
            model_name='albumcart',
            name='album_id',
        ),
        migrations.AddField(
            model_name='albumcart',
            name='album_id',
            field=models.ManyToManyField(through='JazzBluesApp.AlbumCartUser', to='JazzBluesApp.Album'),
        ),
    ]
