# Generated by Django 3.0 on 2021-08-12 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JazzBluesApp', '0007_auto_20210812_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcartuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='eventcartuser',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JazzBluesApp.Event'),
        ),
        migrations.RemoveField(
            model_name='eventcart',
            name='event_id',
        ),
        migrations.AddField(
            model_name='eventcart',
            name='event_id',
            field=models.ManyToManyField(through='JazzBluesApp.EventCartUser', to='JazzBluesApp.Event'),
        ),
        migrations.RemoveField(
            model_name='eventcart',
            name='user_id',
        ),
        migrations.AddField(
            model_name='eventcart',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
