# Generated by Django 3.0 on 2021-08-12 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JazzBluesApp', '0008_auto_20210812_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='albumorder',
            name='album_id',
        ),
        migrations.AlterField(
            model_name='albumorder',
            name='order_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('canceled', 'Canceled')], default='processing', max_length=15),
        ),
        migrations.AlterField(
            model_name='albumorder',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketpurchase',
            name='seat_number',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='AlbumOrderUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JazzBluesApp.Album')),
                ('albumorder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albumorderitems', to='JazzBluesApp.AlbumOrder')),
            ],
        ),
        migrations.AddField(
            model_name='albumorder',
            name='album_id',
            field=models.ManyToManyField(through='JazzBluesApp.AlbumOrderUser', to='JazzBluesApp.Album'),
        ),
    ]
