# Generated by Django 3.0 on 2021-08-12 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0009_auto_20210812_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumorderuser',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 16, 7, 40, 354149)),
        ),
    ]
