# Generated by Django 3.0 on 2021-08-12 14:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JazzBluesApp', '0010_albumorderuser_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2021, 8, 12, 16, 11, 9, 317084))),
            ],
        ),
        migrations.RemoveField(
            model_name='albumorderuser',
            name='order_date',
        ),
        migrations.AddField(
            model_name='albumorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 16, 11, 9, 317084)),
        ),
        migrations.CreateModel(
            name='EventOrderUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JazzBluesApp.Event')),
                ('eventorder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventorderitems', to='JazzBluesApp.EventOrder')),
            ],
        ),
        migrations.AddField(
            model_name='eventorder',
            name='event_id',
            field=models.ManyToManyField(through='JazzBluesApp.EventOrderUser', to='JazzBluesApp.Event'),
        ),
        migrations.AddField(
            model_name='eventorder',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
