# Generated by Django 3.0 on 2021-08-13 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0011_auto_20210812_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumcart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='albumcartuser',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='albumorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 11, 32, 0, 662449)),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 11, 32, 0, 662449)),
        ),
    ]
