# Generated by Django 3.0 on 2021-08-13 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0012_auto_20210813_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='eventcartuser',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='albumorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 12, 15, 33, 407844)),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 12, 15, 33, 408839)),
        ),
    ]
