# Generated by Django 3.0 on 2021-08-13 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0015_auto_20210813_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 20, 8, 27, 439158)),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 20, 8, 27, 440262)),
        ),
        migrations.AlterField(
            model_name='eventorderuser',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
