# Generated by Django 3.0 on 2021-08-17 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0021_auto_20210817_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='address_id',
        ),
        migrations.AddField(
            model_name='venue',
            name='location_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='albumorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 9, 56, 17, 4004)),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 9, 56, 17, 4004)),
        ),
    ]
