# Generated by Django 3.0 on 2021-08-17 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0022_auto_20210817_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 9, 56, 28, 708530)),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 9, 56, 28, 708530)),
        ),
        migrations.AlterField(
            model_name='venue',
            name='location_name',
            field=models.CharField(max_length=100),
        ),
    ]
