# Generated by Django 3.0 on 2021-08-17 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0023_auto_20210817_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='location_name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets_sale_start_date',
        ),
        migrations.AlterField(
            model_name='albumorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 10, 23, 11, 14631)),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 10, 23, 11, 14631)),
        ),
    ]
