# Generated by Django 3.0 on 2021-08-17 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0024_auto_20210817_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='number_of_tickets',
        ),
        migrations.AddField(
            model_name='event',
            name='available_tickets',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='albumorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 10, 30, 37, 111985)),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 10, 30, 37, 120027)),
        ),
    ]
