# Generated by Django 3.0 on 2021-08-17 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0028_auto_20210817_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 11, 48, 9, 93493)),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('concert', 'Concert'), ('festival', 'Festival')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 11, 48, 9, 93493)),
        ),
    ]
