# Generated by Django 3.0 on 2021-08-17 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0029_auto_20210817_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourNews',
            new_name='News',
        ),
        migrations.AlterField(
            model_name='albumorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 13, 56, 11, 45812)),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('concert', 'Concert'), ('festival', 'Festival')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 13, 56, 11, 46811)),
        ),
    ]
