# Generated by Django 3.0 on 2021-08-17 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0030_auto_20210817_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('publish_date', models.DateField(default=datetime.date.today)),
                ('text', models.CharField(max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='albumorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 14, 0, 21, 127319)),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 14, 0, 21, 127319)),
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
