# Generated by Django 3.0 on 2021-08-18 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0036_auto_20210817_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 9, 29, 24, 312978)),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('concert', 'Concert'), ('festival', 'Festival')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 9, 29, 24, 312978)),
        ),
    ]
