# Generated by Django 3.0 on 2021-12-06 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JazzBluesApp', '0037_auto_20210818_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 9, 59, 30, 646079)),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 9, 59, 30, 646079)),
        ),
        migrations.AlterField(
            model_name='venue',
            name='row_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='row_seat_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
